/*
 * generated by Xtext
 */
package org.eclipse.eclipsecon.scoping.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ScopingUiModule extends org.eclipse.eclipsecon.scoping.ui.AbstractScopingUiModule {
	public ScopingUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
