/*
* generated by Xtext
*/
package org.eclipse.eclipsecon.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.eclipse.eclipsecon.services.SpeakerGrammarAccess;

public class SpeakerParser extends AbstractContentAssistParser {
	
	@Inject
	private SpeakerGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.eclipse.eclipsecon.ui.contentassist.antlr.internal.InternalSpeakerParser createParser() {
		org.eclipse.eclipsecon.ui.contentassist.antlr.internal.InternalSpeakerParser result = new org.eclipse.eclipsecon.ui.contentassist.antlr.internal.InternalSpeakerParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getPackageAccess().getGroup(), "rule__Package__Group__0");
					put(grammarAccess.getSpeakerAccess().getGroup(), "rule__Speaker__Group__0");
					put(grammarAccess.getFQNAccess().getGroup(), "rule__FQN__Group__0");
					put(grammarAccess.getFQNAccess().getGroup_1(), "rule__FQN__Group_1__0");
					put(grammarAccess.getPackageAccess().getNameAssignment_1(), "rule__Package__NameAssignment_1");
					put(grammarAccess.getPackageAccess().getSpeakersAssignment_2(), "rule__Package__SpeakersAssignment_2");
					put(grammarAccess.getSpeakerAccess().getNameAssignment_1(), "rule__Speaker__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.eclipse.eclipsecon.ui.contentassist.antlr.internal.InternalSpeakerParser typedParser = (org.eclipse.eclipsecon.ui.contentassist.antlr.internal.InternalSpeakerParser) parser;
			typedParser.entryRulePackage();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SpeakerGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SpeakerGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
