/*
 * generated by Xtext
 */
package org.eclipse.eclipsecon.ui.contentassist

import org.eclipse.eclipsecon.ui.contentassist.AbstractSpeakerProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SpeakerProposalProvider extends AbstractSpeakerProposalProvider {
}
