/*
* generated by Xtext
*/
package org.eclipse.eclipsecon;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LocationStandaloneSetup extends LocationStandaloneSetupGenerated{

	public static void doSetup() {
		new LocationStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

