/*
 * generated by Xtext
 */
package org.eclipse.eclipsecon;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LocationRuntimeModule extends org.eclipse.eclipsecon.AbstractLocationRuntimeModule {

}
