/*
 * generated by Xtext
 */
package org.eclipse.eclipsecon.scoping;

import org.eclipse.xtext.scoping.impl.ImportedNamespaceAwareLocalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ScopingRuntimeModule extends org.eclipse.eclipsecon.scoping.AbstractScopingRuntimeModule {
}
