/*
* generated by Xtext
*/
package org.eclipse.eclipsecon.scoping;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ScopingStandaloneSetup extends ScopingStandaloneSetupGenerated{

	public static void doSetup() {
		new ScopingStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

