/*
* generated by Xtext
*/
package org.eclipse.eclipsecon.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.eclipsecon.services.SpeakerGrammarAccess;

public class SpeakerParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SpeakerGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.eclipsecon.parser.antlr.internal.InternalSpeakerParser createParser(XtextTokenStream stream) {
		return new org.eclipse.eclipsecon.parser.antlr.internal.InternalSpeakerParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Package";
	}
	
	public SpeakerGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SpeakerGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
