/*
 * generated by Xtext
 */
package org.eclipse.eclipsecon.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.eclipsecon.ui.internal.SpeakerActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SpeakerExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SpeakerActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SpeakerActivator.getInstance().getInjector(SpeakerActivator.ORG_ECLIPSE_ECLIPSECON_SPEAKER);
	}
	
}
