/*
* generated by Xtext
*/
package org.eclipse.eclipsecon;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class LocationUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.eclipsecon.ui.internal.LocationActivator.getInstance().getInjector("org.eclipse.eclipsecon.Location");
	}
	
}
