/*
 * generated by Xtext
 */
package org.eclipse.eclipsecon.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConferenceUiModule extends org.eclipse.eclipsecon.ui.AbstractConferenceUiModule {
	public ConferenceUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
