/*
 * generated by Xtext
 */
package org.eclipse.eclipsecon.scoping.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.eclipsecon.scoping.ui.internal.ScopingActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ScopingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ScopingActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ScopingActivator.getInstance().getInjector(ScopingActivator.ORG_ECLIPSE_ECLIPSECON_SCOPING_SCOPING);
	}
	
}
