/*
* generated by Xtext
*/
package org.eclipse.eclipsecon.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.eclipsecon.services.LocationGrammarAccess;

public class LocationParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LocationGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.eclipsecon.parser.antlr.internal.InternalLocationParser createParser(XtextTokenStream stream) {
		return new org.eclipse.eclipsecon.parser.antlr.internal.InternalLocationParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Package";
	}
	
	public LocationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LocationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
