/*
* generated by Xtext
*/
package org.eclipse.eclipsecon;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ConferenceStandaloneSetup extends ConferenceStandaloneSetupGenerated{

	public static void doSetup() {
		new ConferenceStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

