/*
 * generated by Xtext
 */
package org.eclipse.eclipsecon.scoping.ui.contentassist

import org.eclipse.eclipsecon.scoping.ui.contentassist.AbstractScopingProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ScopingProposalProvider extends AbstractScopingProposalProvider {
}
