/*
* generated by Xtext
*/
package org.eclipse.eclipsecon.scoping.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ScopingAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/eclipsecon/scoping/parser/antlr/internal/InternalScoping.tokens");
	}
}
