/*
* generated by Xtext
*/
package org.eclipse.eclipsecon.scoping.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.eclipsecon.scoping.services.ScopingGrammarAccess;

public class ScopingParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ScopingGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.eclipsecon.scoping.parser.antlr.internal.InternalScopingParser createParser(XtextTokenStream stream) {
		return new org.eclipse.eclipsecon.scoping.parser.antlr.internal.InternalScopingParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public ScopingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ScopingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
