/*
* generated by Xtext
*/
package org.eclipse.eclipsecon.scoping;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ScopingUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.eclipsecon.scoping.ui.internal.ScopingActivator.getInstance().getInjector("org.eclipse.eclipsecon.scoping.Scoping");
	}
	
}
