/*
 * generated by Xtext
 */
package org.eclipse.eclipsecon.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.eclipsecon.ui.internal.LocationActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LocationExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LocationActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LocationActivator.getInstance().getInjector(LocationActivator.ORG_ECLIPSE_ECLIPSECON_LOCATION);
	}
	
}
